name: R-CMD-check

on:
  push:
    branches: [ tagteam ]
  pull_request:
    branches: [ tagteam ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    
    env:
      CRAN: https://cran.rstudio.com
      _R_CHECK_FORCE_SUGGESTS_: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y -q libopenmpi-dev openmpi-bin
        echo "LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so" >> $GITHUB_ENV
    
    - name: Verify MPI installation
      run: |
        mpiexec --version
        mpicc -showme:incdirs
        mpicc -showme:libdirs
        mpicc -showme:compile
        mpicc -showme:link
        mpiexec -np 2 hostname
    
    - name: Install R dependencies
      run: |
        Rscript -e "install.packages(c('float'))"
    
    - name: Check R session
      run: |
        Rscript -e "sessionInfo()"
    
    - name: Build and check package
      run: |
        R CMD build --no-resave-data --no-manual --no-build-vignettes .
        R CMD check --as-cran --no-manual --ignore-vignettes ./pbdMPI_*.tar.gz